/**
 * Supabase Edge Function: generate-recipes
 *
 * This is the ONLY place the OpenAI key lives — as a server-side secret, never
 * in the app bundle. The Dishly client calls it via supabase.functions.invoke,
 * so the key is never exposed to browsers/devices.
 *
 * Deploy:
 *   supabase secrets set OPENAI_API_KEY=sk-...        # your (rotated) key
 *   supabase functions deploy generate-recipes
 *
 * Request  body: { query: string, dietary?: string[], allergens?: string[] }
 * Response body: { recipes: Recipe[] }  (shape matches src/data/recipes.ts)
 */

const OPENAI_API_KEY = Deno.env.get('OPENAI_API_KEY');
const MODEL = Deno.env.get('OPENAI_MODEL') ?? 'gpt-4o-mini';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });

// The JSON shape we force OpenAI to return, mirroring the app's Recipe type.
const SYSTEM_PROMPT = `You are a recipe generator for a cooking app called Dishly.
Given a user's craving, return 1-3 recipes as strict JSON. Respect the user's
dietary preferences and NEVER include their listed allergens as ingredients.
Each recipe object must have exactly these fields:
  id (kebab-case slug, prefix "ai-"),
  title (string),
  author (always "Generated by Dishly AI"),
  rating (null),
  prep (integer minutes), cook (integer minutes),
  difficulty ("Easy" | "Medium" | "Hard"),
  dietary (string[] lowercase, e.g. ["vegan"]),
  allergens (string[] lowercase),
  calories (string like "520 kcal per serving · Serves 2"),
  ingredients (array of { name: string, g?: number, text?: string }),
  steps (array of { n: integer, min: integer, template: string }).
Return ONLY: { "recipes": [ ... ] }`;

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });
  if (req.method !== 'POST') return json({ error: 'Method not allowed' }, 405);

  if (!OPENAI_API_KEY) {
    return json({ error: 'OPENAI_API_KEY secret is not set on the function.' }, 500);
  }

  let payload: { query?: string; dietary?: string[]; allergens?: string[] };
  try {
    payload = await req.json();
  } catch {
    return json({ error: 'Invalid JSON body' }, 400);
  }

  const query = (payload.query ?? '').trim();
  if (!query) return json({ error: 'query is required' }, 400);

  const userPrompt = [
    `Craving: ${query}`,
    payload.dietary?.length ? `Dietary preferences: ${payload.dietary.join(', ')}` : '',
    payload.allergens?.length ? `Must avoid allergens: ${payload.allergens.join(', ')}` : '',
  ]
    .filter(Boolean)
    .join('\n');

  try {
    const resp = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${OPENAI_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: MODEL,
        temperature: 0.7,
        response_format: { type: 'json_object' },
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: userPrompt },
        ],
      }),
    });

    if (!resp.ok) {
      const detail = await resp.text();
      return json({ error: 'OpenAI request failed', detail }, 502);
    }

    const data = await resp.json();
    const content = data.choices?.[0]?.message?.content ?? '{"recipes":[]}';
    const parsed = JSON.parse(content);
    const recipes = Array.isArray(parsed.recipes) ? parsed.recipes : [];
    return json({ recipes });
  } catch (err) {
    return json({ error: 'Generation failed', detail: String(err) }, 500);
  }
});
