/**
 * "Find via AI" — the generation seam.
 *
 * Today this runs a deterministic, query-driven matcher over the local recipe
 * set and synthesizes a tailored recipe when nothing matches well, streaming
 * staged progress so the UI can show the user what "the AI" is doing. In Phase 4
 * the body of `generateRecipesForQuery` is replaced by a real model call
 * (Supabase Edge Function / LLM); the signature and the AI_STEPS contract stay
 * identical, so the Results screen doesn't change.
 */
import { isSupabaseConfigured, supabase } from '@/lib/supabase';
import { RECIPES, type Recipe } from './recipes';

/**
 * Recipes conjured at runtime (synthesized AI suggestions) that aren't in the
 * static set. `fetchRecipeById` consults this so Results → detail works for
 * them. In Phase 4 these would be persisted rows instead.
 */
export const generatedById: Record<string, Recipe> = {};

/** The visible pipeline shown while AI results are produced. */
export const AI_STEPS = [
  'Understanding your request',
  'Matching your dietary preferences',
  'Generating recipes',
] as const;

const STOPWORDS = new Set([
  'a', 'an', 'the', 'with', 'and', 'or', 'for', 'me', 'some', 'i', 'want',
  'find', 'recipe', 'recipes', 'dish', 'please', 'to', 'of', 'my',
]);

/** Split a query into meaningful lowercase terms. */
export function queryTerms(query: string): string[] {
  return query
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length > 1 && !STOPWORDS.has(t));
}

/** Score how well a recipe matches the query terms (title + ingredients). */
export function scoreRecipe(recipe: Recipe, terms: string[]): number {
  if (terms.length === 0) return 0;
  const haystack = [
    recipe.title,
    ...recipe.ingredients.map((i) => i.name),
    ...recipe.dietary,
  ]
    .join(' ')
    .toLowerCase();
  return terms.reduce((score, term) => (haystack.includes(term) ? score + 1 : score), 0);
}

/** Ranked local matches for a query, best first (used by "my recipes" too). */
export function rankRecipes(recipes: Recipe[], query: string): Recipe[] {
  const terms = queryTerms(query);
  if (terms.length === 0) return recipes;
  return recipes
    .map((r) => ({ r, s: scoreRecipe(r, terms) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .map((x) => x.r);
}

function titleCase(s: string): string {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}

/**
 * A topical stock photo for an AI recipe, derived from its title keywords.
 * Same free LoremFlickr approach as the catalog; the `lock` (hashed from the
 * title) keeps the same image stable for the same recipe.
 */
export function imageForRecipe(title: string): string {
  const kw = queryTerms(title).slice(0, 2).join(',') || 'food';
  let hash = 0;
  for (let i = 0; i < title.length; i++) hash = (hash * 31 + title.charCodeAt(i)) | 0;
  const lock = (Math.abs(hash) % 100) + 1;
  return `https://loremflickr.com/800/600/${encodeURIComponent(kw)}?lock=${lock}`;
}

/**
 * Synthesize a plausible recipe from the query when nothing matches. This is
 * the placeholder for a real generative call — clearly attributed to Dishly AI.
 */
export function synthesizeRecipe(query: string): Recipe {
  const terms = queryTerms(query);
  const name = terms.length > 0 ? titleCase(terms.slice(0, 3).join(' ')) : 'Chef’s Surprise';
  return {
    id: `ai-${terms.join('-') || 'surprise'}`,
    title: name,
    author: 'Generated by Dishly AI',
    image: imageForRecipe(name),
    rating: null,
    prep: 15,
    cook: 20,
    difficulty: 'Easy',
    dietary: [],
    allergens: [],
    calories: 'Approx. 500 kcal per serving · Serves 2',
    ingredients: [
      { name: `Fresh ${terms[0] ?? 'seasonal'} ingredients`, text: 'to taste' },
      { name: 'Olive oil', g: 15 },
      { name: 'Garlic', text: '2 cloves' },
      { name: 'Salt & pepper', text: 'to taste' },
      { name: 'Fresh herbs', text: 'a handful' },
    ],
    steps: [
      { n: 1, min: 10, template: `Prep the ${terms[0] ?? 'main'} ingredients and gather everything you need.` },
      { n: 2, min: 12, template: 'Heat olive oil, add garlic, and cook the main ingredients until done.' },
      { n: 3, min: 3, template: 'Season to taste, finish with fresh herbs, and serve.' },
    ],
  };
}

/** Coerce a loosely-typed recipe from the model into our Recipe shape. */
function normalizeRecipe(raw: any, index: number): Recipe {
  const slug =
    typeof raw?.id === 'string' && raw.id.length > 0
      ? raw.id
      : `ai-${Date.now()}-${index}`;
  const title = String(raw?.title ?? 'Dishly AI Recipe');
  return {
    id: slug.startsWith('ai-') ? slug : `ai-${slug}`,
    title,
    author: 'Generated by Dishly AI',
    image:
      typeof raw?.image === 'string' && raw.image.length > 0 ? raw.image : imageForRecipe(title),
    rating: null,
    prep: Number(raw?.prep) || 15,
    cook: Number(raw?.cook) || 20,
    difficulty: ['Easy', 'Medium', 'Hard'].includes(raw?.difficulty) ? raw.difficulty : 'Easy',
    dietary: Array.isArray(raw?.dietary) ? raw.dietary.map(String) : [],
    allergens: Array.isArray(raw?.allergens) ? raw.allergens.map(String) : [],
    calories: String(raw?.calories ?? 'Approx. 500 kcal per serving'),
    ingredients: Array.isArray(raw?.ingredients)
      ? raw.ingredients.map((i: any) => ({
          name: String(i?.name ?? ''),
          g: typeof i?.g === 'number' ? i.g : undefined,
          text: i?.text != null ? String(i.text) : undefined,
        }))
      : [],
    steps: Array.isArray(raw?.steps)
      ? raw.steps.map((s: any, n: number) => ({
          n: Number(s?.n) || n + 1,
          min: Number(s?.min) || 5,
          template: String(s?.template ?? ''),
        }))
      : [],
  };
}

/**
 * Call the server-side OpenAI Edge Function (where the API key lives). Returns
 * null on any failure so the caller can fall back to the local matcher — the
 * feature never becomes a dead end just because the function isn't deployed.
 */
async function generateViaOpenAI(
  query: string,
  prefs?: { dietary?: string[]; allergens?: string[] },
): Promise<Recipe[] | null> {
  if (!isSupabaseConfigured) return null;
  try {
    const { data, error } = await supabase.functions.invoke('generate-recipes', {
      body: { query, dietary: prefs?.dietary ?? [], allergens: prefs?.allergens ?? [] },
    });
    if (error || !data?.recipes?.length) return null;
    return (data.recipes as any[]).map(normalizeRecipe);
  } catch {
    return null;
  }
}

/**
 * Produce AI results for a query. Emits progress via `onStep(index)` as each
 * stage completes. Prefers the real OpenAI Edge Function; falls back to the
 * local ranked matches (or a synthesized recipe) when it's unavailable.
 */
export async function generateRecipesForQuery(
  query: string,
  onStep?: (stepIndex: number) => void,
  prefs?: { dietary?: string[]; allergens?: string[] },
): Promise<Recipe[]> {
  const step = (i: number, ms: number) =>
    new Promise<void>((resolve) =>
      setTimeout(() => {
        onStep?.(i);
        resolve();
      }, ms),
    );

  await step(0, 300);
  // Kick off the real generation while the "matching" stage animates.
  const remotePromise = generateViaOpenAI(query, prefs);
  await step(1, 300);
  const remote = await remotePromise;
  const local = rankRecipes(RECIPES, query);
  const results = remote ?? (local.length > 0 ? local : [synthesizeRecipe(query)]);
  await step(2, 300);

  // Register anything not already addressable so the detail screen can load it.
  for (const r of results) generatedById[r.id] = r;
  return results;
}
